### ISSUE TITLE
IDMatchNotFoundException

### ISSUE THREAD

**Issue by Odixi** [Odixi/UI-course#1]
Room 115 - getItem(String itemID)
Throws IDMatchNotFoundException even though The item should exist in that room
eg. SmartItem matching id h1r1L002 not found in the room h001r001

To get it, just open user view as user with the rights to any item.

**Comment by Rikkokiri** [comment]
Alright, I was finally able to get this error when running the program. I'm working on it now.

**Comment by Rikkokiri** [comment]
I've found out that there's an appliance that doesn't have an ID in the list.

Printing items Hashtable from the RoomContentComponent:

> RoomContentComponent: item Temperature has key h1r2S001
> RoomContentComponent: item Bedside lamp (left) has key h1r2L003
> RoomContentComponent: item Bedside lamp (right) has key h1r2L002
> RoomContentComponent: item Ceiling light has key h1r2L001
> RoomContentComponent: item Appliance 3 has key

Where this appliance is came from is still a mystery to me but I'm constantly working on it.

**Comment by Rikkokiri** [comment]
Alright, bug fixed.
