### ISSUE TITLE
Changes made by admin not saved

### ISSUE THREAD

**Issue by Rikkokiri** [Odixi/UI-course#2]
I noticed that changes made by admin are not being saved to the user's view file. My bug of course, but I thought I'd report this so you people know that I'm working on it.

**Comment by Rikkokiri** [comment]
Have you @Odixi experiences this issue too? Because my Eclipse just keeps crashing so the error might not (hopefully) be in the code.

**Comment by Odixi** [comment]
Yeps, View files get wiped when I try to save changes in adminVIew

**Comment by Rikkokiri** [comment]
It works! YASSSS!

**Comment by Odixi** [comment]
Yayy!!!
