### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by Odixi** [Odixi/UI-course#4]
For some reason a sensor in first houses big bedroom has a name 'Temperature' but type is 'light'(sensor).
I've no Idea why.

Also, is it possible to just add more houses/rooms/items to the houses.xml directly? (or is java code needed or does it break the view configurations?) I'd like to add controllers and different sensors to test them in UI.

**Comment by Rikkokiri** [comment]
I'll take a look at that temperature issue.

Sure you can add stuff directly.
It does not exactly break the views. New stuff just won't be added to already generated view files. But you can just delete those when you add stuff and they will be generated just fine.

I want to add the functionality for updating the house structure in view files but it's hardly a priority. I'll do it if I have time at some point. The following week is going to be a crazy one.

**Comment by Rikkokiri** [comment]
Adding the break statements to switches fixed this issue.
