### ISSUE TITLE
UI update discussion

### ISSUE THREAD

**Issue by Odixi** [Odixi/UI-course#7]
I've made an update() method to the SmartUI, which should update the current views items accordingly with the server. It basically makes every item component to update itself using RMI. So when server wants clients to update, just run this method.

@vogelfanger What are your thought on this? Did you have some other idea on how the updates should be made?

**Comment by vogelfanger** [comment]
I had forgotten about the RMI...
That makes it a whole lot easier. My plan was to handle the whole process separately, but using RMI is much better. I think the update() method in SmartUI should still run the updates through access() method to separate regular server updates from event triggered updates made by the user. After that it should be ready to use.

**Comment by vogelfanger** [comment]
The access() method Javadoc actually suggests that it might be unecessary to use with RPC. I'll add it in anyway just to be safe.

**Comment by Odixi** [comment]
Do what you think is best. As long as it works.

FYI I haven't tested the update method in any way, so I've no idea if it works.

**Comment by Odixi** [comment]
Looks like the UI updating isn't working.

I'm not really sure how the UI push should work (Haven't really looked into it), but I'm quite sure that this:

```
public void register() {
    try{
        shsystem.getUpdater().register(this);
    } catch (RemoteException e) {   e.printStackTrace();}
}
```

won't work.

Getting the remote object with RMI and then running the register() method won't do anything on the server end. Which means that the UI won't be registered to the broadcast list. I don't know how it should be done to make it broadcast messages over internet. I'll leave it to you.

If you can't figure it out, I have an idea to how handle the UI updating but it's not pretty. So please, tell me if you can't get it to work and I'll do it the other way. (Preferably early so I have time before deadline)

Also, the ui updates should be done every time these methods are run in SmartHSystemImp:
//---------- Lights ------------------------

```
public void turnLightOn(String houseID, String roomID, String itemID)throws RemoteException, IDMatchNotFoundException, IDTypeMismatch;

public void turnLightOff(String houseID, String roomID, String itemID)throws RemoteException, IDTypeMismatch, IDMatchNotFoundException;

//----------- Appliances & audio devices -----------------------

public void turnApplianceOn(String houseID, String roomID, String itemID) throws RemoteException, IDTypeMismatch, IDMatchNotFoundException;

public void turnApplianceOff(String houseID, String roomID, String itemID) throws RemoteException, IDTypeMismatch, IDMatchNotFoundException;

boolean setAudioVolume(String houseID, String roomID, String itemID, int volume) throws RemoteException, IDMatchNotFoundException, IDTypeMismatch;

//----------- Controllers ----------------------------------------

public boolean setControllerValue(String houseID, String roomID, String itemID, double value) throws RemoteException, IDTypeMismatch, IDMatchNotFoundException;
```
